version: '3.9'
services:

  ihm:
    image: php:apache
    container_name: ihm
    environment:
      USERNAME: toto
      PASSWORD: python
    volumes:
      - ./website:/var/www/html
    depends_on:
      - studentlist
    ports:
      - "8080:80"
    networks:
    - reseauprive
  
  studentlist:
    container_name: studentlist
    image: studentageapi:v1
    volumes:
      - '$PWD/simple_api/student_age.json:/data/student_age.json'
    networks:
    - reseauprive
    
  registry:
    container_name: registry
    image: registry:2
    ports:
      - '9500:5000'
    networks:
    - registry
  
  registry-ui:
    image: joxit/docker-registry-ui:main
    depends_on: 	
      - registry
    ports:
      - 80:80
    networks:
      - registry
    environment:
      - REGISTRY_URL="http://registry:9500"
      - REGISTRY_TITLE=Docker Registry UI
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - DELETE_IMAGES=true
      - SINGLE_REGISTRY=true
      - CATALOG_ELEMENTS_LIMIT=10


networks:
  reseauprive:
  registry:
